'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const {runApprovedCollectorSlice,captureCollectorListingPage,persistCollectorListingObservation,collectorShellQuote}=require('../src/supported_tool_runner.js');
function mock(t,overrides={}) {
 const run=fs.mkdtempSync(path.join(__dirname,'runner-fixture-'));t.after(()=>fs.rmSync(run,{recursive:true,force:true}));
 const calls=[],item={id:'123',url:'https://aagag.com/issue/?idx=123',title:'safe'};
 const ctx={rootDir:path.resolve(__dirname,'..'),runDir:run,reviewedIds:['123'],tools:{
  exec_command:async a=>{calls.push(['exec',a]);if(a.cmd.startsWith('# DAILYK_VERIFY_EVIDENCE')){try{return {exit_code:0,output:cp.execFileSync('/bin/bash',['-c',a.cmd],{encoding:'utf8',stdio:['ignore','pipe','pipe']})};}catch(e){return {exit_code:1,output:String(e.stderr||e.message)};}}return {exit_code:0,output:JSON.stringify(a.cmd.includes(' pending ')?[item]:{complete:false})};},
  mcp__cua_repl__js:async a=>{calls.push(['browser',a]);return {content:[{type:'text',text:JSON.stringify([{requestedId:'123',status:'observed'}])}]};},
  apply_patch:async patch=>{calls.push(['patch',patch]);const lines=patch.split('\n');for(let i=0;i<lines.length;i++){if(!lines[i].startsWith('*** Add File: '))continue;const file=lines[i].slice(14),data=[];while(++i<lines.length&&lines[i].startsWith('+'))data.push(lines[i].slice(1));i--;assert.ok(file.startsWith(run+'/'));fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data.join('\n')+'\n');}return {};},
  ...overrides
 }};return {ctx,calls,run};
}
const listing={url:'https://aagag.com/issue/',observedAt:'2026-10-09T02:00:00Z',items:[{id:'123',title:'safe',url:'https://aagag.com/issue/?idx=123'}],pages:[{number:2,url:'https://aagag.com/issue/?page=2'}]};
test('unreviewed titles never open browser',async t=>{const {calls,ctx}=mock(t);ctx.reviewedIds=[];const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'title_review_required');assert.equal(calls.filter(x=>x[0]==='browser').length,0);});
test('reviewed slice stages verifies atomically promotes and only then summarizes',async t=>{const {calls,ctx,run}=mock(t);const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'checkpointed');assert.deepEqual(calls.map(x=>x[0]),['exec','browser','patch','exec','exec']);assert.equal(r.persistence.verified,true);assert.equal(r.persistence.durability,'file_and_parent_directory_fsync');const bytes=fs.readFileSync(path.join(run,'posts/123.json'));assert.equal(r.persistence.files[0].sha256,crypto.createHash('sha256').update(bytes).digest('hex'));assert.deepEqual(JSON.parse(bytes),{requestedId:'123',status:'observed'});});
test('patch success without written evidence never claims checkpointed',async t=>{const {ctx,calls}=mock(t,{apply_patch:async()=>({})});const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'persistence_unverified');assert.equal(r.checkpointUpdated,false);assert.equal(r.browserRetryAllowed,false);assert.equal(calls.filter(x=>x[0]==='exec'&&x[1].cmd.includes(' summary ')).length,0);});
test('changed staged JSON never replaces existing evidence',async t=>{const {ctx,run}=mock(t);fs.mkdirSync(path.join(run,'posts'));fs.writeFileSync(path.join(run,'posts/123.json'),'OLD EVIDENCE');const original=ctx.tools.apply_patch;ctx.tools.apply_patch=async patch=>{await original(patch);const staged=patch.split('\n').find(x=>x.startsWith('*** Add File: ')).slice(14);fs.writeFileSync(staged,'{"requestedId":"123","status":"changed"}\n');return {};};const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'persistence_unverified');assert.equal(fs.readFileSync(path.join(run,'posts/123.json'),'utf8'),'OLD EVIDENCE');});
test('explicit staging error is not automatically retried or verified as success',async t=>{let writes=0;const {ctx}=mock(t,{apply_patch:async()=>{writes++;return {isError:true};}});const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'persistence_unverified');assert.equal(writes,1);});
test('tool denial is not retried',async t=>{let n=0;const {ctx}=mock(t,{mcp__cua_repl__js:async()=>{n++;return {isError:true,content:[{type:'text',text:'denied'}]};}});const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'tool_stopped');assert.equal(n,1);});
test('runtime circuit breaker persists the failed record then pauses',async t=>{const {ctx}=mock(t,{mcp__cua_repl__js:async()=>({content:[{type:'text',text:JSON.stringify([{requestedId:'123',status:'failed',stopBatch:true}])}]})});const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'paused');assert.equal(r.persistence.verified,true);});
test('CAPTCHA stops without approval inference',async t=>{const {ctx}=mock(t,{mcp__cua_repl__js:async()=>({content:[{type:'text',text:JSON.stringify([{requestedId:'123',status:'blocked_or_missing'}])}]})});const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'paused');assert.equal(r.automaticCaptchaApproval,false);});
test('unexpected ID cannot write a path',async t=>{const {ctx}=mock(t,{mcp__cua_repl__js:async()=>({content:[{type:'text',text:JSON.stringify([{requestedId:'../../bad'}])}]})});await assert.rejects(()=>runApprovedCollectorSlice(ctx),/Unexpected/);});
test('duplicate returned IDs cannot be checkpointed twice',async t=>{const {ctx}=mock(t,{mcp__cua_repl__js:async()=>({content:[{type:'text',text:JSON.stringify([{requestedId:'123'},{requestedId:'123'}])}]})});await assert.rejects(()=>runApprovedCollectorSlice(ctx),/duplicate/);});
test('empty browser slice is not successful progress',async t=>{const {ctx,calls}=mock(t,{mcp__cua_repl__js:async()=>({content:[{type:'text',text:'[]'}]})});const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'tool_stopped');assert.equal(calls.filter(x=>x[0]==='patch').length,0);});
test('guessed pagination link cannot navigate',async t=>{const {ctx,calls}=mock(t);Object.assign(ctx,{pageNumber:9,phase:'initial',url:'https://aagag.com/issue/?page=9',previousPage:{pages:[{number:8,url:'https://aagag.com/issue/?page=8'}]}});await assert.rejects(()=>captureCollectorListingPage(ctx),/observed prior-page/);assert.equal(calls.length,0);});
test('first captured listing can persist after manifest init without another browser call',async t=>{const {ctx,calls,run}=mock(t);Object.assign(ctx,{phase:'initial',pageNumber:1});const r=await persistCollectorListingObservation(ctx,listing);assert.equal(r.status,'checkpointed');assert.equal(r.persistence.verified,true);assert.equal(calls.filter(x=>x[0]==='browser').length,0);assert.equal(JSON.parse(fs.readFileSync(path.join(run,'listings/initial-0001.json'))).observedAt,listing.observedAt);});
test('listing capture also requires verified persistence before claiming success',async t=>{const {ctx}=mock(t,{apply_patch:async()=>({}),mcp__cua_repl__js:async()=>({content:[{type:'text',text:JSON.stringify(listing)}]})});Object.assign(ctx,{phase:'initial',pageNumber:1,url:listing.url});const r=await captureCollectorListingPage(ctx);assert.equal(r.status,'persistence_unverified');});
test('checkpoint failure preserves verified evidence without reporting checkpointed',async t=>{const {ctx,run}=mock(t);const original=ctx.tools.exec_command;ctx.tools.exec_command=async a=>a.cmd.includes(' summary ')?{exit_code:1,output:'checkpoint unavailable'}:original(a);const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'checkpoint_update_failed');assert.equal(r.persistence.verified,true);assert.ok(fs.existsSync(path.join(run,'posts/123.json')));});
test('JSON evidence quotes and shell metacharacters are data not shell commands',async t=>{const title="Korean ㅋ ' \" $(not-a-command); `not-a-command`";const {ctx,run}=mock(t,{mcp__cua_repl__js:async()=>({content:[{type:'text',text:JSON.stringify([{requestedId:'123',status:'observed',title}])}]})});assert.equal((await runApprovedCollectorSlice(ctx)).status,'checkpointed');assert.equal(JSON.parse(fs.readFileSync(path.join(run,'posts/123.json'))).title,title);});
test('path newline rejected',()=>assert.throws(()=>collectorShellQuote('/tmp/x\nY')));
test('exhausted queue derives resweep requirement from traversal rather than unresolved holds',async t=>{for(const done of [true,false]){const {ctx,calls}=mock(t);ctx.tools.exec_command=async a=>({exit_code:0,output:JSON.stringify(a.cmd.includes(' pending ')?[]:{complete:false,nativeCommentCoverageComplete:false,verificationHeldIDs:['999'],listingCoverageComplete:done,passes:{initial:true,resweep:done}})});const r=await runApprovedCollectorSlice(ctx);assert.equal(r.status,'queue_exhausted');assert.equal(r.resweepStillRequired,!done);assert.equal(calls.filter(x=>x[0]==='browser').length,0);}});
const {managedCollectorOperation}=require('../src/supported_tool_runner.js');
test('managed slice requires guard and closes denial durably',async()=>{
 const calls=[];const state={revision:2,lease:{fence:1},status:'running'};
 const ctx={rootDir:'/tmp/code',runDir:'/tmp/run',statePath:'/tmp/state.json',runtimeRevision:1,sourceSha256:'a'.repeat(64),owner:'test',tools:{exec_command:async a=>{calls.push(a.cmd);return {exit_code:0,output:JSON.stringify(a.cmd.includes("'finish'")?{revision:3,status:'paused_requires_user'}:state)};},mcp__cua_repl__js:async()=>{calls.push('BROWSER');throw new Error('Permission denied')}}};
 const r=await managedCollectorOperation(ctx,async c=>c.tools.mcp__cua_repl__js({code:'test'}));
 assert.equal(r.runtimeStatus,'paused_requires_user');assert.match(calls[0],/begin/);assert.match(calls[0],/runDir/);assert.match(calls[1],/guard/);assert.equal(calls[2],'BROWSER');assert.match(calls[3],/finish/);
});
test('failed guard prevents any browser access',async()=>{
 let n=0,browser=0;const ctx={rootDir:'/tmp/code',runDir:'/tmp/run',statePath:'/tmp/state.json',runtimeRevision:1,sourceSha256:'a'.repeat(64),owner:'test',tools:{exec_command:async()=>++n===1?{exit_code:0,output:JSON.stringify({revision:2,lease:{fence:1}})}:{exit_code:1,output:'paused'},mcp__cua_repl__js:async()=>{browser++;}}};
 const r=await managedCollectorOperation(ctx,async c=>c.tools.mcp__cua_repl__js({}));assert.equal(browser,0);assert.equal(r.status,'runtime_reconciliation_required');
});
