'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {runSupervisedCollectorTick,validateProjection,confirmedCas}=require('../src/supervised_tick.js');
const clone=x=>JSON.parse(JSON.stringify(x));
function fixture(){
 const p={runKey:'a'.repeat(64),window:{start:'2026-10-08T00:00:00Z',end:'2026-10-09T00:00:00Z'},sourceSha256:'b'.repeat(64),privateEvidenceDigest:'c'.repeat(64),localRevision:1,progress:{observedRecords:null,qualifiers:null,candidates:null},coverage:{listing:false,resweep:false,nativeComments:false,complete:false},checkpointAt:'2026-10-09T01:00:00Z'};
 let state=null,sha='a'.repeat(40),calls=[],runs=0,journal=[];
 const remote={read:async()=>({mainSha:sha,state:clone(state)}),compareAndSwap:async a=>{calls.push(a);assert.equal(a.force,false);if(a.expectedMainSha!==sha||JSON.stringify(a.expectedState)!==JSON.stringify(state))return {status:'conflict'};state=clone(a.nextState);sha=(sha[0]==='a'?'b':'c').repeat(40);return {status:'committed',mainSha:sha};}};
 const local={inspect:async()=>({available:true,projection:clone(p),runtimeRevision:p.localRevision,sourceSha256:p.sourceSha256,runtimeStatus:'ready'}),journal:async e=>{journal.push(e)},execute:async({guard})=>{await guard();runs++;p.localRevision+=2;p.progress.observedRecords=6;return {status:'checkpointed'}}};
 return {ctx:{operationId:'tick-1',claimNonce:'0123456789abcdef0123456789abcdef',owner:'worker',remote,local},p,calls,journal,getRuns:()=>runs,getState:()=>state,setState:s=>{state=s},advanceMain:()=>{sha='d'.repeat(40)}};
}
test('claims CAS before collecting and publishes only allowlisted projection',async()=>{const f=fixture();const r=await runSupervisedCollectorTick(f.ctx);assert.equal(r.status,'checkpointed');assert.equal(f.getRuns(),1);assert.equal(f.calls.length,2);assert.equal(f.calls[0].nextState.status,'running');assert.equal(f.getState().projection.progress.observedRecords,6);assert.ok(f.journal.length>=6);assert.equal(JSON.stringify(f.getState()).includes('posts/'),false)});
test('same tick retry is idempotent',async()=>{const f=fixture();await runSupervisedCollectorTick(f.ctx);assert.equal((await runSupervisedCollectorTick(f.ctx)).status,'already_completed');assert.equal(f.getRuns(),1)});
test('active or expired remote claim is never stolen',async()=>{for(const expiry of ['2000-01-01T00:00:00Z','2099-01-01T00:00:00Z']){const f=fixture();await runSupervisedCollectorTick(f.ctx);const s=f.getState();s.status='running';s.lease={owner:'other',expiresAt:expiry};f.setState(s);assert.equal((await runSupervisedCollectorTick({...f.ctx,operationId:'tick-2'})).reason,'active_or_uncertain_previous_execution');assert.equal(f.getRuns(),1)}});
test('repository-only CAS conflict rebases without duplicate browser read',async()=>{const f=fixture(),old=f.ctx.remote.compareAndSwap;let i=0;f.ctx.remote.compareAndSwap=async a=>{if(i++===0){f.advanceMain();return {status:'conflict'}}return old(a)};const r=await runSupervisedCollectorTick(f.ctx);assert.equal(r.status,'checkpointed');assert.equal(f.getRuns(),1)});
test('unknown CAS after commit reconciles by exact readback',async()=>{const f=fixture(),old=f.ctx.remote.compareAndSwap;f.ctx.remote.compareAndSwap=async a=>{await old(a);throw new Error('network uncertain')};assert.equal((await runSupervisedCollectorTick(f.ctx)).status,'checkpointed');assert.equal(f.getRuns(),1)});
test('unknown CAS without commit never starts browser or blind retries',async()=>{const f=fixture();let n=0;f.ctx.remote.compareAndSwap=async()=>{n++;return {status:'unknown'}};await assert.rejects(()=>runSupervisedCollectorTick(f.ctx),/unconfirmed/);assert.equal(f.getRuns(),0);assert.equal(n,1)});
test('missing private state marks explicit loss preserving fixed window',async()=>{const f=fixture();await runSupervisedCollectorTick(f.ctx);f.ctx.local.inspect=async()=>({available:false});const r=await runSupervisedCollectorTick({...f.ctx,operationId:'tick-2'});assert.equal(r.reason,'private_evidence_unavailable');assert.equal(f.getState().status,'evidence_missing');assert.deepEqual(f.getState().projection.window,f.p.window);assert.equal(f.getRuns(),1)});
test('remote private mismatch prevents work',async()=>{const f=fixture();await runSupervisedCollectorTick(f.ctx);f.p.localRevision++;const r=await runSupervisedCollectorTick({...f.ctx,operationId:'tick-2'});assert.equal(r.reason,'remote_private_checkpoint_mismatch');assert.equal(f.getRuns(),1)});
test('denial pauses and cannot automatically restart',async()=>{const f=fixture();f.ctx.local.execute=async()=>{throw new Error('denied')};const r=await runSupervisedCollectorTick(f.ctx);assert.equal(r.status,'paused');assert.equal(f.getState().status,'paused_requires_review');assert.equal((await runSupervisedCollectorTick({...f.ctx,operationId:'tick-2'})).status,'not_started')});
test('private fields and fabricated zero missing counts rejected',()=>{const f=fixture();assert.throws(()=>validateProjection({...f.p,rawComments:[]}));const p=clone(f.p);delete p.progress.candidates;assert.throws(()=>validateProjection(p));});
test('changed remote fence prevents tool side effect',async()=>{const f=fixture();f.ctx.local.execute=async({guard})=>{const s=f.getState();s.revision++;f.setState(s);await guard();throw new Error('should never execute')};assert.equal((await runSupervisedCollectorTick(f.ctx)).status,'reconciliation_required');assert.equal(f.getRuns(),0)});
test('journal failure occurs before any CAS',async()=>{const f=fixture();f.ctx.local.journal=async()=>{throw new Error('disk full')};await assert.rejects(()=>runSupervisedCollectorTick(f.ctx),/disk full/);assert.equal(f.calls.length,0);assert.equal(f.getRuns(),0)});
test('final local run cannot silently rebind remote claim',async()=>{const f=fixture();f.ctx.local.execute=async()=>{f.p.runKey='d'.repeat(64);return {status:'checkpointed'}};const r=await runSupervisedCollectorTick(f.ctx);assert.equal(r.status,'paused');assert.equal(f.getState().projection.runKey,'a'.repeat(64))});
test('verified terminal state stops bounded continuations',async()=>{const f=fixture();let terminal=false,old=f.ctx.local.inspect;f.ctx.local.execute=async()=>{terminal=true;f.p.coverage={listing:true,resweep:true,nativeComments:true,complete:true};return {status:'queue_exhausted'}};f.ctx.local.inspect=async()=>({...await old(),runtimeStatus:terminal?'verified_complete':'ready'});const r=await runSupervisedCollectorTick(f.ctx);assert.equal(f.getState().status,'terminal');assert.equal(r.nextWake,'new_cycle_review_required')});
test('different invocation nonces cannot share winning claim',async()=>{
 const f=fixture();let reads=0,release;const barrier=new Promise(r=>release=r);const oldRead=f.ctx.remote.read;
 f.ctx.remote.read=async()=>{if(++reads<=2){const snap=await oldRead();if(reads===2)release();await barrier;return snap;}return oldRead();};
 const results=await Promise.allSettled([runSupervisedCollectorTick(f.ctx),runSupervisedCollectorTick({...f.ctx,claimNonce:'abcdef0123456789abcdef0123456789'})]);assert.equal(f.getRuns(),1);assert.equal(results.filter(r=>r.status==='rejected').length,1);
});
const {reconcileSupervisedCollector}=require('../src/supervised_tick.js');
test('recovery never overrides active lease',async()=>{const f=fixture();await runSupervisedCollectorTick(f.ctx);const s=f.getState();s.status='running';s.lease={owner:'worker',expiresAt:'2099-01-01T00:00:00Z'};await assert.rejects(()=>reconcileSupervisedCollector({...f.ctx,operationId:'recovery'},{mode:'resume',reference:'approval',priorExecutionEnded:true}),/Active lease/)});
test('lost evidence recovery preserves fixed window',async()=>{const f=fixture();await runSupervisedCollectorTick(f.ctx);f.getState().status='evidence_missing';const r=await reconcileSupervisedCollector({...f.ctx,operationId:'recovery'},{mode:'restart_fixed_window',reference:'reviewed-restart',priorExecutionEnded:true});assert.equal(r.status,'ready');assert.equal(f.getState().operationId,'recovery')});
test('explicit review can rebind remote-ready local revision without changing evidence',async()=>{const f=fixture();await runSupervisedCollectorTick(f.ctx);f.p.localRevision++;const r=await reconcileSupervisedCollector({...f.ctx,operationId:'recovery-2'},{mode:'resume',reference:'reviewed-local-pause',priorExecutionEnded:true});assert.equal(r.status,'ready');assert.equal(f.getState().projection.localRevision,f.p.localRevision)});
